M48
; DRILL file {KiCad 7.0.0-da2b9df05c~163~ubuntu20.04.1} date mié 22 feb 2023 20:56:47
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-22T20:56:47-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0-da2b9df05c~163~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X136.0Y-111.5
X163.0Y-111.5
T2
X138.41Y-74.98
X149.44Y-74.86
X160.39Y-74.86
T0
M30
